/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MiButton {
    'outline': string;
    'text': string;
  }
  interface MiButtonAttributes extends StencilHTMLAttributes {
    'outline'?: string;
    'text'?: string;
  }

  interface MiSelectionCard {
    'description': string;
    'extraInfo': string;
  }
  interface MiSelectionCardAttributes extends StencilHTMLAttributes {
    'description'?: string;
    'extraInfo'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MiButton': Components.MiButton;
    'MiSelectionCard': Components.MiSelectionCard;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'mi-button': Components.MiButtonAttributes;
    'mi-selection-card': Components.MiSelectionCardAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLMiButtonElement extends Components.MiButton, HTMLStencilElement {}
  var HTMLMiButtonElement: {
    prototype: HTMLMiButtonElement;
    new (): HTMLMiButtonElement;
  };

  interface HTMLMiSelectionCardElement extends Components.MiSelectionCard, HTMLStencilElement {}
  var HTMLMiSelectionCardElement: {
    prototype: HTMLMiSelectionCardElement;
    new (): HTMLMiSelectionCardElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'mi-button': HTMLMiButtonElement
    'mi-selection-card': HTMLMiSelectionCardElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'mi-button': HTMLMiButtonElement;
    'mi-selection-card': HTMLMiSelectionCardElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
